Convert html to react -> header.jsx and Homepage.jsx
prasadhonrao/devcamper pull request #50
Opened 2024-09-17 09:51 UTC by AkankshShigwan

2024-09-17 15:37 UTC, prasadhonrao commented on ui/src/components/Header.jsx
Import sequnce should be like following

1. react specific
2. Third part like font awesome
3. Project specific files like boostrap.css

2024-09-17 15:38 UTC, prasadhonrao commented on ui/src/components/bootcamps.js
Filename should be Bootcamps.jsx

2024-09-17 15:38 UTC, prasadhonrao commented on ui/src/components/login.js
Filename should be Login.jsx

2024-09-17 15:40 UTC, prasadhonrao commented on ui/src/components/register.jsx
Do we need a separate component for Register page. Are we using this anywhere else in the project?

2024-09-17 15:41 UTC, prasadhonrao requested changes
Comments added in individual files.

2024-09-19 09:11 UTC, AkankshShigwan commented on ui/src/components/register.jsx
not we will have only one registration page

2024-09-22 19:02 UTC, prasadhonrao commented
Close by #50

2024-09-22 19:02 UTC, closed without merging