Akanksha bootcamp details
prasadhonrao/devcamper pull request #76
Opened 2024-10-11 11:56 UTC by AkankshShigwan

working on this @prasadhonrao please review this -> I am still working on this it's not the final code

2024-10-11 12:13 UTC, prasadhonrao requested changes

2024-10-11 12:13 UTC, prasadhonrao commented on ui/src/components/courses.jsx
Pls correct file name casing

2024-10-11 12:13 UTC, prasadhonrao commented on ui/src/components/courses.jsx
> +import Table from 'react-bootstrap/Table';
I think you can define a Course componene for this.

2024-10-11 12:13 UTC, prasadhonrao commented on ui/src/index.css
> +  background-color: #e05433 !important;
Avoid using !important as it gets difficult to track the CSS hierarchy

2024-10-11 12:13 UTC, prasadhonrao commented on ui/src/pages/bootcamps/ManageCoursesPage.jsx
> +    <>
When you are returning a section, fragment i.e. <> is not required

2024-10-14 06:58 UTC, AkankshShigwan commented on ui/src/components/courses.jsx
done

2024-10-14 07:00 UTC, AkankshShigwan commented on ui/src/components/courses.jsx
> +import Table from 'react-bootstrap/Table';
It is previous code which is not merge with development branch that's why you can see this changes. In bootcamp details page not using courses data or structure.

2024-10-14 07:02 UTC, AkankshShigwan commented on ui/src/index.css
> +  background-color: #e05433 !important;
noted

2024-10-14 07:03 UTC, AkankshShigwan commented on ui/src/pages/bootcamps/ManageCoursesPage.jsx
> +    <>
noted

2024-10-14 07:22 UTC, AkankshShigwan commented
@prasadhonrao please review this and also, I have added comments for the changes

2024-10-14 08:40 UTC, merged